import { InferGetServerSidePropsType, GetServerSideProps } from 'next'
import Link from 'next/link'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
//components
import Search from '../components/Search'
import ListCharacters from '../components/ListCharacters'
import Pagination from '../components/Pagination'
//Apollo-Graphql
import { gql } from "@apollo/client";
import client from "../apollo-client";


const Home = ({ characters}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RickandMorty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search />
      <ListCharacters characters={ characters }/>
      <Pagination />
    </div>
  )
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async ({query}) => {
  const page = Number(query?.page) || 1
  try {
    const {data} = await client.query({
      query: gql `
        query getCharacters {
          characters(page:${page}) {
            results{
              id
              name
              image
            }
          }
        }
      `
      })

      return {
          props: { 
              characters: data.characters.results
          }
      }
  } catch (error) {
    return {notFound: true,}
  }
  
}

export default Home
