import { InferGetServerSidePropsType, GetServerSideProps } from 'next'
import Link from 'next/link'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
//components
import Header from '../components/Header'
import Card from '../components/Card'
import Pagination from '../components/Pagination'
//Apollo-Graphql
import { gql } from "@apollo/client";
import client from "../apollo-client";


type Characters = {
  id: number,
  name: string,
  image: string
}

type HomeProps = {
  characters: Characters[]
}

// const GET_CHARACTERS = (page: number) => gql `
// query getCharacters {
//   characters(page:${page}) {
//     results{
//       id
//       name
//       image
//     }
//   }
// }
// `
export const getServerSideProps: GetServerSideProps<HomeProps> = async ({query}) => {
  const page = Number(query?.page) || 1
  const {data} = await client.query({
  query: gql `
  query getCharacters {
    characters(page:${page}) {
      results{
        id
        name
        image
      }
    }
  }
  `
  })

  if (!data) {
  return {notFound: true,}
  }

  return {
      props: { 
          characters: data.characters.results
      }
  }
}



const Home = ({ characters}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RickandMorty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.Header }>
        <Header />
      </section>
      <main className={styles.main}>
        <section className={ styles.Characters}>
          {
            characters.map(item => (
                <Card 
                  key={item.id} 
                  id={item.id} 
                  image={item.image} 
                  title={item.name}
                />
            ))
          }
        </section>
        
        <section className={ styles.Pagination }>
          <Pagination />
        </section>
        
      </main>
    </div>
  )
}

export default Home
