import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { InferGetStaticPropsType, GetStaticProps } from 'next'

import { gql, useQuery } from "@apollo/client";
import client from "../apollo-client";
import { useEffect, useState } from 'react';

type Characters = {
  id: number,
  name: string,
  img: string
}

type HomeProps = {
  characters: Characters[]
}

const GET_CHARACTERS = (page: number) => gql `
query getCharacters {
  characters(page:${page}) {
    results{
      id
      name
      image
    }
  }
}
`

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const {data} = await client.query({
    query: GET_CHARACTERS(1)
  })

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { 
      characters: data.characters.results
    }
  }
}


const Home = ({ characters}: InferGetStaticPropsType<typeof getStaticProps>) => {
  const [ page, setPage ] = useState(1)
  const { data, loading, error } = useQuery(GET_CHARACTERS(page))

  // useEffect(() => {
  //   if(page !== 1) {
  //   }
  // },[page])
    
  console.log("data: ", data)
  console.log("characters: ",characters)

  return (
    <div className={styles.container}>
      <Head>
        <title>RickandMorty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hola mundo</h1>
        {
          characters.map(item => (
            <div key={item.id}>
              <h2>{item.id}</h2>
              <h2>{item.name}</h2>
            </div>
          ))
        }
        <button onClick={ () => setPage(prev => prev + 1)}>Next</button>
      </main>
    </div>
  )
}

export default Home
